Major changes due to merge r9147-11125 from trunk.
We now have the current version of the ParamNode, as well as I/O classes 
methods available in this branch.

No new functionality is available compared to the previous version.

Optimization is still completely deactivated. Only the electrostatic PDE 
was tested with the condaxi example. 

All occurrences of INGEGLIB and MEMTRACE have been removed, as well as 
the generation of .deb and .mem files. This functionality should
be covered by more advanced libraries (e.g. google perftools, likwid) in 
the future.

diff --git a/share/doc/developer/makedoc.sh.in b/share/doc/developer/makedoc.sh.in
--- a/share/doc/developer/makedoc.sh.in
+++ b/share/doc/developer/makedoc.sh.in
@@ -3,10 +3,14 @@
 MODE=$1
 
 function clean {
-    echo " "
-    echo " Deleting Doxygen Documentation for CFS++ in"
+    echo "========================================"
+    echo " Cleaning up developer doc directory... "
+    echo "========================================"
+
+    echo "============================================="
+    echo " Deleting Doxygen Documentation for CFS++ in "
     echo " @CMAKE_CURRENT_SOURCE_DIR@/html"
-    echo " "
+    echo "============================================="
 
     rm -rfv @CMAKE_CURRENT_SOURCE_DIR@/html
     RETCODE=$?
@@ -15,30 +19,82 @@ function clean {
 	echo " Error while deleting Doxygen Doc.!"
 	exit 1;
     fi
+
+    rm -fv @CMAKE_CURRENT_SOURCE_DIR@/develManual/*.bbl
+    rm -fv @CMAKE_CURRENT_SOURCE_DIR@/develManual/*.aux
+    rm -fv @CMAKE_CURRENT_SOURCE_DIR@/develManual/*.toc
+    rm -fv @CMAKE_CURRENT_SOURCE_DIR@/develManual/*.pdf
+    rm -fv @CMAKE_CURRENT_SOURCE_DIR@/develManual/*.log
+    rm -fv @CMAKE_CURRENT_SOURCE_DIR@/develManual/*.blg
+    rm -fv @CMAKE_CURRENT_SOURCE_DIR@/develManual/*.out
+    rm -fv @CMAKE_CURRENT_SOURCE_DIR@/develManual/*.tpt
+
+    echo "==================================="
+    echo " Done cleaning up!"
+    echo "==================================="
+
 }
 
 function build {
+    echo "====================================="
+    echo " Generating CFS++ developer's manual "
+    echo "====================================="
+
+    # Copy university logos to manual directory
+    cp @CMAKE_CURRENT_SOURCE_DIR@/../auxilliaries/Pics/ls_am_klu.pdf @CMAKE_CURRENT_SOURCE_DIR@/develManual/pics
+    cp @CMAKE_CURRENT_SOURCE_DIR@/../auxilliaries/Pics/cfs-logo.pdf @CMAKE_CURRENT_SOURCE_DIR@/develManual/pics
+    cp @CMAKE_CURRENT_SOURCE_DIR@/../auxilliaries/Pics/lse_logo.pdf @CMAKE_CURRENT_SOURCE_DIR@/develManual/pics
+
+    # Auto generate bootstrap_devel_machine.txt from distro.sh and bootstrap_devel_machine.sh
+    cat @CMAKE_CURRENT_SOURCE_DIR@/../../scripts/distro.sh | sed '/^Help\(\)/, /^fi/d' | sed '/^      while \:$/, /^      done$/d' > @CMAKE_CURRENT_SOURCE_DIR@/develManual/attachments/bootstrap_devel_machine.txt
+    echo "echo \$OSSTR" >> @CMAKE_CURRENT_SOURCE_DIR@/develManual/attachments/bootstrap_devel_machine.txt
+    cat @CMAKE_CURRENT_SOURCE_DIR@/../../scripts/bootstrap_devel_machine.sh | sed '/^\#\!\/bin\/sh/, /^\. /d' >> @CMAKE_CURRENT_SOURCE_DIR@/develManual/attachments/bootstrap_devel_machine.txt
+
+    cd @CMAKE_CURRENT_SOURCE_DIR@/develManual
+    DOCUMENT=develManual
+
+    # Apply syntax coloring to files in sources directory
+    sources/pygmentize.sh $PWD/sources $PWD
+
+    @PDFLATEX_COMPILER@ $DOCUMENT && \
+    @BIBTEX_COMPILER@ $DOCUMENT && \
+    @PDFLATEX_COMPILER@ $DOCUMENT && \
+    @PDFLATEX_COMPILER@ $DOCUMENT && \
+    @PDFLATEX_COMPILER@ $DOCUMENT && \
+    thumbpdf $DOCUMENT && \
+    @PDFLATEX_COMPILER@ $DOCUMENT
+    RETCODE_DEVMAN=$?
+
     #
     # Generate CFS++ documentation using doxygen
     #
-    echo " "
-    echo " Generating Doxygen Documentation for CFS++"
-    echo " "
-
+    echo " ==========================================="
+    echo " Generating Doxygen Documentation for CFS++ "
+    echo " ==========================================="
+    
     @CMAKE_CURRENT_SOURCE_DIR@/DoxygenConfig/changeDate.sh \
-    @CMAKE_CURRENT_SOURCE_DIR@/DoxygenConfig/footerTemplate.html \
-    @CMAKE_CURRENT_SOURCE_DIR@/DoxygenConfig/footer.html
+	@CMAKE_CURRENT_SOURCE_DIR@/DoxygenConfig/footerTemplate.html \
+	@CMAKE_CURRENT_SOURCE_DIR@/DoxygenConfig/footer.html
     @DOXYGEN_EXECUTABLE@ @DOXY_CONFIG@
-    RETCODE=$?
+    RETCODE_DOXY=$?
 
-    if [ "$RETCODE" != "0" ]; then
-	echo " Could not make help!"
+    if [ "$RETCODE_DOXY" != "0" ]; then
+	echo " Could not make Doxygen help!"
 	exit 1;
     else
 	echo " "
-	echo " See @CMAKE_CURRENT_SOURCE_DIR@/html/index.html for doc"
+	echo " See @CMAKE_CURRENT_SOURCE_DIR@/html/index.html for doc."
 	echo " "
     fi
+
+    if [ "$RETCODE_DEVMAN" != "0" ]; then
+	echo " Could not make developer's manual!"
+	exit 1;
+    else
+	echo " See @CMAKE_CURRENT_SOURCE_DIR@/devManual/devManual.pdf developer's manual."
+	echo " "
+    fi
+
 }
 
 case "$MODE" in
diff --git a/share/scripts/cfstool b/share/scripts/cfstool
--- a/share/scripts/cfstool
+++ b/share/scripts/cfstool
@@ -114,7 +114,11 @@ SetANSYSParameters()
 	    ANS_ARCH=linia32;
 	    LIB=/lib ;;
 	X86_64)
-	    ANS_ARCH=linop64;
+	    if [ "$SUBARCH" = "OPTERON" ]; then
+		ANS_ARCH=linop64;
+	    else
+		ANS_ARCH=linem64t;
+	    fi
 	    LIB=/lib64 ;;
 	IA64)
 	    ANS_ARCH=linia64;
@@ -124,7 +128,7 @@ SetANSYSParameters()
     # If ANSYS directory does not exist, try to determine it from executable.
     if [ ! -d "$ANSYS_ROOT_DIR" ]
     then
-        PGFLIB=`$LDD $CFS_EXE | grep libpgf90.so | cut -d' ' -f3`
+        PGFLIB=`$LDD $CFSTOOL_EXE | grep libpgf90.so | cut -d' ' -f3`
 
         if [ -f "$PGFLIB" ]
         then
@@ -133,19 +137,19 @@ SetANSYSParameters()
         fi
     fi
 
-    if [ ! -d "$ANSYS_ROOT_DIR" ]
-    then
+#    if [ ! -d "$ANSYS_ROOT_DIR" ]
+#    then
+#
+#
+#	echo "Cannot find root directory of ANSYS:"
+#	echo "  $ANSYS_ROOT_DIR"
+#	echo "Please set either environment variable ANSYS_ROOT_DIR"
+#	echo "or edit $HOME/.nacsrc."
+#	exit 1
+#    fi
 
 
-	echo "Cannot find root directory of ANSYS:"
-	echo "  $ANSYS_ROOT_DIR"
-	echo "Please set either environment variable ANSYS_ROOT_DIR"
-	echo "or edit $HOME/.nacsrc."
-	exit 1
-    fi
-
-
-    export LD_LIBRARY_PATH=$LIB:$ANSYS_ROOT_DIR/ansys/syslib/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/customize/misc/$ANS_ARCH:$LD_LIBRARY_PATH
+    export LD_LIBRARY_PATH=$CFS_ROOT_DIR$LIB/$ARCH_STR:$CFS_ROOT_DIR$LIB/$ARCH_STR/v110/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/syslib/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/customize/misc/$ANS_ARCH:$LD_LIBRARY_PATH
 }
 
 SetGIDParameters()
@@ -187,11 +191,11 @@ then
     unset ANSYS_ROOT_DIR_TEMP
 fi
 
-CFS_DIST_TYPE="GID"
+CFS_DIST_TYPE="ANSYS"
 
 if [ "$CFS_DIST_TYPE" = "" ]
 then 
-    echo "Cannot determine distribution type of CFS."
+    echo "Cannot determine distribution type of CFSTOOL."
     echo "CFS_DIST_TYPE should be one of GID / ANSYS."
     exit 1
 fi
@@ -208,7 +212,7 @@ then
 fi
 
 # Set path to CFS executable
-CFS_EXE=$CFS_ROOT_DIR/bin/$ARCH_STR/cfstoolbin
+CFSTOOL_EXE=$CFS_ROOT_DIR/bin/$ARCH_STR/cfstoolbin
 
 # Set parameters according to distribution type.
 case "$CFS_DIST_TYPE" in
@@ -226,7 +230,7 @@ esac
 if [ "$BINARY_TREE" = "0" ]; then
     if [ ! -d "$CFS_ROOT_DIR/$LIB/$ARCH_STR" ]
     then 
-        echo "Cannot find CFS library path for architecture $ARCH_STR."
+        echo "Cannot find CFSTOOL library path for architecture $ARCH_STR."
         exit 2
     fi
 fi
@@ -237,28 +241,28 @@ then
 fi
 
 # Check if we have the necessary executable for the current arch.
-if [ ! -e $CFS_EXE ]
+if [ ! -e $CFSTOOL_EXE ]
 then 
-    echo "Cannot find CFS executable for architecture $ARCH_STR."
+    echo "Cannot find CFSTOOL executable for architecture $ARCH_STR."
     exit 3
 fi
 
 if [ "$CFS_SCRIPT_DEBUG" = "1" ]
 then
     echo "Libraries:"
-    $LDD $CFS_EXE
+    $LDD $CFSTOOL_EXE
 fi
 
 # Check if some system libraries are missing.
-CFS_EXE_LDD=`$LDD $CFS_EXE | grep "not found"`
+CFSTOOL_EXE_LDD=`$LDD $CFSTOOL_EXE | grep "not found"`
 
-if [ "$CFS_EXE_LDD" != "" ]
+if [ "$CFSTOOL_EXE_LDD" != "" ]
 then 
     echo "Some dependencies on system libraries could not be resolved."
     echo "These were:"
-    echo "$CFS_EXE_LDD";
+    echo "$CFSTOOL_EXE_LDD";
     echo
-    echo "CFS++ depends on the following packages on $DISTRO $DISTRO_VER:"
+    echo "CFSTOOL depends on the following packages on $DISTRO $DISTRO_VER:"
     GivePackageHint $DISTRO $DISTRO_VER
     echo "Please install the required packages."
     exit 4
@@ -267,7 +271,7 @@ fi
 # Execute the CFS exutable with arguments from this script
 if [ $# != 0 ]
 then
- $CFS_EXE "$@";
+ $CFSTOOL_EXE "$@";
 else
- $CFS_EXE;
+ $CFSTOOL_EXE;
 fi
