- Added proper error messages in case common.sh or distro.sh could not be found.   This might happen if one uses a symlink to execute cfs without settings the   correct paths. - Corrected version history: current version is 11.09, not 11.08

diff --git a/share/scripts/cfs b/share/scripts/cfs
--- a/share/scripts/cfs
+++ b/share/scripts/cfs
@@ -4,7 +4,12 @@
 # CFS_DIST/bin under the name 'cfs'
 
 # Source shell script for setting some common variables.
-. `dirname $0`/common.sh
+COMMON_SH=`dirname $0`/common.sh
+if [ ! -x "$COMMON_SH" ]; then
+  echo "Could not execute $COMMON_SH. Exiting..."
+  exit 1
+fi
+source $COMMON_SH
 
 SUSEPackageHint()
 {
