- Added bootstrap scripts for a MinGW Windows development environment. - Adapted Linux bootstrap script for upcoming RedHat Enterprise Linux 7. - CFS++ starter shell scripts now also run inside MSYS environment.

diff --git a/share/scripts/cfs b/share/scripts/cfs
--- a/share/scripts/cfs
+++ b/share/scripts/cfs
@@ -54,7 +54,7 @@ SetANSYSParameters()
     esac
 
     # If ANSYS directory does not exist, try to determine it from executable.
-    if [ ! -d "$ANSYS_ROOT_DIR" ]
+    if [ "$OS" = "LINUX" ] && [ ! -d "$ANSYS_ROOT_DIR" ]
     then
         PGFLIB=`$LDD $CFS_EXE | grep libpgf90.so | cut -d' ' -f3`
 
@@ -219,15 +219,17 @@ then
 fi
 
 # Check if some system libraries are missing.
-CFS_EXE_LDD=`$LDD $CFS_EXE | grep "not found"`
+if [ "$OS" = "LINUX" ]; then
+    CFS_EXE_LDD=`$LDD $CFS_EXE | grep "not found"`
 
-if [ "$CFS_EXE_LDD" != "" ]
-then 
-    echo "Some dependencies on system libraries could not be resolved."
-    echo "These were:"
-    echo "$CFS_EXE_LDD";
-    echo
-    exit 4
+    if [ "$CFS_EXE_LDD" != "" ]
+    then 
+        echo "Some dependencies on system libraries could not be resolved."
+        echo "These were:"
+        echo "$CFS_EXE_LDD";
+        echo
+        exit 4
+    fi
 fi
 
 # Check if OMP_NUM_THREADS has been previously set and set it to 1 if not.
