- This merge brings the revisions r11127 until r11283 from the trunk to   the FESpace branch.
- The merge has been conducted for the following directories which are
  relevant in building the documentation:

  source/cplreader
  share/scripts
  share/doc
  cmake_modules

  All other directories are NOT affected by this merge.

- The intent is to move the cplreader documentation into the share/doc
  directory and to build the documentation in the build directory and
  not the source directory anymore.

diff --git a/share/scripts/cfs b/share/scripts/cfs
--- a/share/scripts/cfs
+++ b/share/scripts/cfs
@@ -1,10 +1,15 @@
-#!/bin/bash
+#!/bin/sh
 
 # This is the start script for CFS. It should be placed in
 # CFS_DIST/bin under the name 'cfs'
 
 # Source shell script for setting some common variables.
-. `dirname $0`/common.sh
+COMMON_SH=`dirname $0`/common.sh
+if [ ! -x "$COMMON_SH" ]; then
+  echo "Could not execute $COMMON_SH. Exiting..."
+  exit 1
+fi
+. $COMMON_SH
 
 SUSEPackageHint()
 {
@@ -149,7 +154,8 @@ SetANSYSParameters()
 #    fi
 
 
-    export LD_LIBRARY_PATH=$CFS_ROOT_DIR$LIB/$ARCH_STR:$CFS_ROOT_DIR$LIB/$ARCH_STR/v110/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/syslib/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/customize/misc/$ANS_ARCH:$LD_LIBRARY_PATH
+    LD_LIBRARY_PATH=$CFS_ROOT_DIR$LIB/$ARCH_STR:$CFS_ROOT_DIR$LIB/$ARCH_STR/v110/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/syslib/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/customize/misc/$ANS_ARCH:$LD_LIBRARY_PATH
+    export LD_LIBRARY_PATH
 }
 
 SetGIDParameters()
@@ -159,7 +165,8 @@ SetGIDParameters()
 
 # Set XML schema root path
 if [ -r $CFS_ROOT_DIR/share/xml/CFS-Simulation/CFS.xsd ]; then
-    export CFS_SCHEMA_ROOT=$CFS_ROOT_DIR/share/xml
+    CFS_SCHEMA_ROOT=$CFS_ROOT_DIR/share/xml
+    export CFS_SCHEMA_ROOT
 fi
 
 # Get settings concerning the distribution type of CFS: GiD/ANSYS
